/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./index.{js,ts}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#5B8FB9",
        "primary-container": "#7BAFD4",
        "primary-fixed": "#D6E6F5",
        "primary-fixed-dim": "#A3C7E2",
        "on-primary": "#ffffff",
        "on-primary-container": "#f0f7ff",
        secondary: "#E8734A",
        "secondary-container": "#F09A7A",
        "secondary-fixed": "#FDDDD1",
        "on-secondary": "#ffffff",
        tertiary: "#2E9E5E",
        "tertiary-container": "#37B86D",
        "tertiary-fixed": "#C8F5D8",
        "tertiary-fixed-dim": "#6ED898",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f0fff5",
        error: "#D64045",
        "error-container": "#FFE0E1",
        "on-error": "#ffffff",
        "on-error-container": "#8C1D20",
        surface: "#F8F9FC",
        "surface-dim": "#D8DAE2",
        "surface-bright": "#F8F9FC",
        "surface-container": "#EEF0F6",
        "surface-container-low": "#F2F4F9",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#E6E8F0",
        "surface-container-highest": "#DFE1EA",
        "surface-variant": "#DFE1EA",
        "on-surface": "#1A1D24",
        "on-surface-variant": "#454B5C",
        "on-background": "#1A1D24",
        background: "#F8F9FC",
        outline: "#6E7587",
        "outline-variant": "#BFC4D4",
        "inverse-surface": "#2C2F38",
        "inverse-on-surface": "#EEF0F8",
        "inverse-primary": "#A3C7E2",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["PlusJakartaSans"],
        label: ["PlusJakartaSans"],
      },
      borderRadius: {
        DEFAULT: 4,
        sm: 4,
        md: 8,
        lg: 12,
        xl: 16,
        "2xl": 24,
        "3xl": 32,
        full: 9999,
      },
    },
  },
  plugins: [],
};
