/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./index.{js,ts}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#0058bc",
        "primary-container": "#0070eb",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "on-primary-fixed": "#001a41",
        "on-primary-fixed-variant": "#004493",
        secondary: "#405e96",
        "secondary-container": "#a1befd",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#2d4c83",
        "on-secondary-fixed": "#001a41",
        "on-secondary-fixed-variant": "#26467d",
        tertiary: "#006b27",
        "tertiary-container": "#008733",
        "tertiary-fixed": "#72fe88",
        "tertiary-fixed-dim": "#53e16f",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f7fff2",
        "on-tertiary-fixed": "#002107",
        "on-tertiary-fixed-variant": "#00531c",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#f9f9ff",
        "surface-dim": "#d8d9e5",
        "surface-bright": "#f9f9ff",
        "surface-container": "#ecedf9",
        "surface-container-low": "#f1f3fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8f3",
        "surface-container-highest": "#e0e2ed",
        "surface-variant": "#e0e2ed",
        "surface-tint": "#005bc1",
        "on-surface": "#181c23",
        "on-surface-variant": "#414755",
        "on-background": "#181c23",
        background: "#f9f9ff",
        outline: "#717786",
        "outline-variant": "#c1c6d7",
        "inverse-surface": "#2d3039",
        "inverse-on-surface": "#eef0fc",
        "inverse-primary": "#adc6ff",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["PlusJakartaSans"],
        label: ["PlusJakartaSans"],
      },
      borderRadius: {
        DEFAULT: 4,
        sm: 4,
        md: 8,
        lg: 12,
        xl: 16,
        "2xl": 24,
        "3xl": 32,
        full: 9999,
      },
    },
  },
  plugins: [],
};
